import type { Source } from '@/components/ui/Sources'

// Order = order of first citation on the page, so footnote numbers read 1, 2, 3… top to bottom.
export const CONVERGINT_SOURCES: Source[] = [
  {
    id: 'sdm-2025',
    title: 'Convergint Named #1 Systems Integrator by SDM Magazine For Eighth Year in a Row',
    publisher: 'Convergint',
    date: 'Aug 11, 2025',
    url: 'https://www.convergint.com/press-releases/convergint-named-1-systems-integrator-by-sdm-magazine-for-eighth-year-in-a-row/',
    note: '$2.6 billion global systems integrator; over 10,000 colleagues; more than 220 locations; #1 in SDM Top Systems Integrators for 8 years.',
  },
  {
    id: 'edwards',
    title: 'Convergint expands partnership with Edwards across South Carolina',
    publisher: 'Security Worldmarket',
    date: 'Oct 12, 2021',
    url: 'https://www.securityworldmarket.com/na/News/Business-News/convergint-expands-partnership-with-edwards-across-south-carolina',
    note: '"One of the largest Edwards dealers in the world."',
  },
  {
    id: 'nfpa-72',
    title: 'NFPA 72 Code Development',
    publisher: 'National Fire Protection Association',
    url: 'https://www.nfpa.org/codes-and-standards/nfpa-72-standard-development/72',
    note: 'NFPA 72, National Fire Alarm and Signaling Code.',
  },
  {
    id: 'nfpa-2001',
    title: 'NFPA 2001 Standard Development',
    publisher: 'National Fire Protection Association',
    url: 'https://www.nfpa.org/codes-and-standards/nfpa-2001-standard-development/2001',
    note: 'NFPA 2001, Standard on Clean Agent Fire Extinguishing Systems.',
  },
  {
    id: 'firesystems-switches',
    title: 'Understanding the Difference Between Waterflow, Tamper, and Supervisory Switches',
    publisher: 'Fire Systems, Inc.',
    date: 'Feb 17, 2026',
    url: 'https://firesystems.net/2026/02/17/understanding-the-difference-between-waterflow-tamper-and-supervisory-switches/',
    note: 'Waterflow switch signals an alarm; valve tamper switch signals the panel when a valve is closed.',
  },
  {
    id: 'nfpa-13',
    title: 'NFPA 13 Standard Development',
    publisher: 'National Fire Protection Association',
    url: 'https://www.nfpa.org/codes-and-standards/nfpa-13-standard-development/13',
    note: 'NFPA 13, Standard for the Installation of Sprinkler Systems.',
  },
  {
    id: 'ufgs-28-31-76',
    title: 'UFGS 28 31 76: Interior Fire Alarm and Mass Notification System',
    publisher: 'Whole Building Design Guide (USACE / NAVFAC / AFCEC)',
    date: 'Aug 2020',
    url: 'https://www.wbdg.org/FFC/DOD/UFGS/UFGS%2028%2031%2076.pdf',
    note: 'IDC / NAC / SLC circuits, remote and graphic annunciators, DACT signal transmission.',
  },
  {
    id: 'nfsa-supervising',
    title: 'Understanding the Role of Supervising Station Alarm Systems and Sprinkler Monitoring',
    publisher: 'National Fire Sprinkler Association',
    date: 'Mar 13, 2024',
    url: 'https://nfsa.org/2024/03/13/supervising-station-alarm-systems-and-sprinkler-monitoring/',
    note: 'Supervising stations immediately retransmit fire alarm signals to the communications center (NFPA 72, 26.2.1.2).',
  },
  {
    id: 'ufgs-21-22-00',
    title: 'UFGS 21 22 00: Clean Agent Fire Extinguishing Systems',
    publisher: 'Whole Building Design Guide (USACE / NAVFAC / AFCEC)',
    date: 'Aug 2026',
    url: 'https://www.wbdg.org/FFC/DOD/UFGS/UFGS%2021%2022%2000.pdf',
    note: 'Releasing control unit, pre-discharge signals, time delay and abort stations, cylinder low-pressure switch.',
  },
  {
    id: 'daily-herald-hq',
    title: 'Bell Works in Hoffman Estates adds three more tenants, including largest to date',
    publisher: 'Daily Herald',
    date: 'July 3, 2024',
    url: 'https://www.dailyherald.com/?p=1301823',
    note: 'Convergint "currently located in neighboring Schaumburg."',
  },
  {
    id: 'ssn-schaumburg',
    title: 'Convergint moves Chicago area operations into a new facility',
    publisher: 'Security Systems News',
    url: 'https://www.securitysystemsnews.com/article/convergint-moves-chicago-area-operations-new-facility',
    note: 'Headquarters moved from Buffalo Grove to Schaumburg.',
  },
]
